### PR TITLE
feat!: types and names cleanup

### PR DESCRIPTION
**Pull request by chybisov**
Some refactoring of the callbacks aka hooks names + types refactoring + fixes for tests.

The types and names of the callbacks were too general.

### CODE REVIEW

**Comment by chybisov** [comment]
@Abhikumar98 we will need to update our v2 migration guide once this is merged 🙂

**Review by Abhikumar98 — APPROVED** [review]
lgtm

**Comment by chybisov** [comment]
```ts
export interface InternalExecutionSettings {
  acceptExchangeRateUpdateHook: AcceptExchangeRateUpdateHook
  switchChainHook: SwitchChainHook
  updateRouteHook: UpdateRouteHook
  updateTransactionRequest?: TransactionRequestUpdate
  executeInBackground: boolean
  infiniteApproval: boolean
}
```

@Abhikumar98 @Addminus do we want to rename `updateTransactionRequest` -> `updateTransactionRequestHook` to be consistent on this?

**Review by Addminus — DISMISSED** [review]
Please Ping me once merged, i'll update the docs to reflect these changes

**Comment by Addminus** [comment]
> ```ts
> export interface InternalExecutionSettings {
>   acceptExchangeRateUpdateHook: AcceptExchangeRateUpdateHook
>   switchChainHook: SwitchChainHook
>   updateRouteHook: UpdateRouteHook
>   updateTransactionRequest?: TransactionRequestUpdate
>   executeInBackground: boolean
>   infiniteApproval: boolean
> }
> ```
> 
> @Abhikumar98 @Addminus do we want to rename `updateTransactionRequest` -> `updateTransactionRequestHook` to be consistent on this?

Yes if we update some external hook names now, we should take the time and change them to all be consistent with each other.

**Review by Addminus — APPROVED** [review]
Looks good

**Pull request merged**
